### ISSUE TITLE
Общие параметры запросов

### ISSUE THREAD

**Issue by ASBunny** [KirillBelovTest/VKLink#1]
Возможно ли явное указание языка (параметр lang)? 
При попытке воспользоваться примером из readme все имена пользователей указаны в английском варианте, что делает невозможным различение имен Александр и Alexander:

{<|"id" -> 620, "first_name" -> "Yury", "last_name" -> "Baskakov", 
  "can_access_closed" -> False, "is_closed" -> True, 
  "bdate" -> "8.8.1985"|>

**Comment by KirillBelovTest** [comment]
Было нельзя. Теперь можно. Большое спасибо - исправил.
